name: CI - Build & Scan

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - "apps/backend/**"
      - "apps/frontend/**"
      - "scripts/**"
      - ".github/workflows/**"

env:
  REGISTRY: blr.vultrcr.com/devopsassignment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # REQUIRED for git tags

    - name: Login to Vultr Container Registry
      uses: docker/login-action@v3
      with:
        registry: blr.vultrcr.com
        username: ${{ secrets.VULTR_CR_USERNAME }}
        password: ${{ secrets.VULTR_CR_PASSWORD }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Build Backend
      if: contains(github.event.head_commit.message, 'backend') || true
      run: |
        VERSION=$(scripts/next-version.sh backend)
        echo "BACKEND_VERSION=$VERSION" >> $GITHUB_ENV

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --provenance=false \
          --sbom=false \
          --push \
          -t $REGISTRY/backend:$VERSION \
          apps/backend

        git tag backend-v$VERSION
        git push origin backend-v$VERSION

    - name: Cooldown before frontend build
      run: sleep 20

    - name: Build Frontend
      if: contains(github.event.head_commit.message, 'frontend') || true
      run: |
        VERSION=$(scripts/next-version.sh frontend)
        echo "FRONTEND_VERSION=$VERSION" >> $GITHUB_ENV

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --provenance=false \
          --sbom=false \
          --push \
          -t $REGISTRY/frontend:$VERSION \
          apps/frontend

        git tag frontend-v$VERSION
        git push origin frontend-v$VERSION

    - name: Trivy Scan Backend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/backend:${{ env.BACKEND_VERSION }}
        severity: CRITICAL
        exit-code: 1

